apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: prodcatalog-ns # aws-observability
  name: test-app
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-2048
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-2048
    spec:   
      containers:
      - name: test-app
        image: jojiisacth/logcreator:latest   
      