apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  namespace: amazon-cloudwatch 
  labels:
    app: prometheus-server
spec:
  replicas: 1
  
  selector:
    matchLabels:
      app: prometheus-server
  template:
    metadata:
      labels:
        app: prometheus-server
    spec:
      serviceAccountName: adot-collector
      containers:
        - name: prometheus
          image: prom/prometheus
          args:
            - "--storage.tsdb.retention.time=12h"
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
            - "--web.enable-remote-write-receiver"
          ports:
            - containerPort: 9090
          resources:
            requests:
              cpu: 500m
              memory: 500M
            limits:
              cpu: 500m
              memory: 500M
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
            - name: prometheus-storage-volume
              mountPath: /prometheus/
      volumes:
        - name: prometheus-config-volume
          configMap:
            defaultMode: 420
            name: prometheus-server-conf
  
        - name: prometheus-storage-volume
          emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:

  name: prometheus-service

  namespace: amazon-cloudwatch 
  labels:
    app: prometheus-server
spec:
  ports:
    - name: "http"
      port: 9090
      targetPort: 9090
  selector:
    app: prometheus-server
---